name: Publish with Maven

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
